"""
AGENMATICA - Unit tests for V5: Schedules & Manual Posts.
TDD-004: scheduled_time persists in ISO format.
TDD-005: is_manual flag distinguishes user-created from AI-generated posts.
"""

import pytest
from datetime import date, time

from app.models.models import (
    Band, User, PlanType,
    StrategicBatch, StrategicPost,
    BatchStatus, BatchTimeframe,
)


# ─── TDD-004: Schedules ───────────────────────────────

def test_strategic_post_accepts_scheduled_time():
    """StrategicPost can be created with a scheduled_time value."""
    user = User(email="sched@test.com", hashed_password="x")
    band = Band(name="Sientes", owner=user, plan=PlanType.STARTER)
    batch = StrategicBatch(band=band, timeframe=BatchTimeframe.WEEKLY)
    post = StrategicPost(
        batch=batch,
        platform="instagram",
        concept_title="Expectativa",
        narrative_goal="Generar hype",
        scheduled_date=date(2026, 5, 15),
        scheduled_time=time(20, 0),
    )
    assert post.scheduled_date == date(2026, 5, 15)
    assert post.scheduled_time == time(20, 0)


def test_strategic_post_scheduled_time_defaults_none():
    """scheduled_time is nullable — omitting it leaves it as None."""
    user = User(email="sched@test.com", hashed_password="x")
    band = Band(name="Sientes", owner=user, plan=PlanType.STARTER)
    batch = StrategicBatch(band=band, timeframe=BatchTimeframe.WEEKLY)
    post = StrategicPost(
        batch=batch,
        platform="tiktok",
        concept_title="Identidad",
        narrative_goal="Marca",
    )
    assert post.scheduled_time is None


def test_manual_draft_batch_status():
    """BatchStatus.MANUAL_DRAFT is a valid status value."""
    assert BatchStatus.MANUAL_DRAFT == "manual_draft"
    assert BatchStatus.MANUAL_DRAFT in list(BatchStatus)


def test_manual_draft_batch_creation():
    """A StrategicBatch can be created with MANUAL_DRAFT status."""
    user = User(email="manual@test.com", hashed_password="x")
    band = Band(name="Los Solos", owner=user, plan=PlanType.STARTER)
    batch = StrategicBatch(
        band=band,
        timeframe="manual",
        status=BatchStatus.MANUAL_DRAFT,
    )
    assert batch.status == BatchStatus.MANUAL_DRAFT


# ─── TDD-005: is_manual flag ─────────────────────────

def test_ai_post_is_not_manual_by_default():
    """AI-generated posts should have is_manual=False (or None before DB flush)."""
    user = User(email="ai@test.com", hashed_password="x")
    band = Band(name="Sientes", owner=user, plan=PlanType.STARTER)
    batch = StrategicBatch(band=band, timeframe=BatchTimeframe.WEEKLY)
    post = StrategicPost(
        batch=batch,
        platform="instagram",
        concept_title="AI-generated concept",
        narrative_goal="Generated by strategist agent",
    )
    assert not post.is_manual  # None or False both mean AI-generated


def test_manual_post_is_manual_true():
    """User-created posts must be flagged with is_manual=True."""
    user = User(email="manual@test.com", hashed_password="x")
    band = Band(name="Sientes", owner=user, plan=PlanType.STARTER)
    batch = StrategicBatch(
        band=band,
        timeframe="manual",
        status=BatchStatus.MANUAL_DRAFT,
    )
    post = StrategicPost(
        batch=batch,
        platform="facebook",
        concept_title="Mi idea manual",
        narrative_goal="Lo escribí yo",
        scheduled_date=date(2026, 6, 1),
        scheduled_time=time(18, 30),
        is_manual=True,
        is_approved=False,
    )
    assert post.is_manual is True
    assert post.scheduled_time == time(18, 30)
    assert not post.is_approved


def test_manual_post_can_have_no_concept_title():
    """Manual post without AI ideation fields is valid (pure caption only)."""
    user = User(email="manual@test.com", hashed_password="x")
    band = Band(name="Sientes", owner=user, plan=PlanType.STARTER)
    batch = StrategicBatch(band=band, timeframe="manual", status=BatchStatus.MANUAL_DRAFT)
    post = StrategicPost(
        batch=batch,
        platform="instagram",
        caption="Texto directo sin concepto previo.",
        is_manual=True,
    )
    assert post.concept_title is None
    assert post.narrative_goal is None
    assert post.caption == "Texto directo sin concepto previo."
    assert post.is_manual is True


def test_manual_draft_endpoint_response_contract():
    """Simulate the /planner/manual-draft response shape."""
    # Replicate what the endpoint returns after DB insert
    mock_response = {
        "id": 99,
        "batch_id": 10,
        "platform": "tiktok",
        "concept_title": "Show recapitulation",
        "narrative_goal": "Capitalizar el momentum",
        "caption": None,
        "hashtags": [],
        "scheduled_date": "2026-06-15",
        "scheduled_time": "21:00:00",
        "is_approved": False,
        "is_manual": True,
        "event_id": None,
        "parent_post_id": None,
        "created_at": "2026-04-04T12:00:00+00:00",
    }
    assert mock_response["is_manual"] is True
    assert mock_response["caption"] is None
    assert mock_response["scheduled_time"] == "21:00:00"
