"""Add band miembros y contexto

Revision ID: 16ae00b756b1
Revises: 
Create Date: 2026-03-29 21:20:36.159934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ae00b756b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_posts', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'generated_posts', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_posts', type_='foreignkey')
    op.drop_column('generated_posts', 'campaign_id')
    # ### end Alembic commands ###
