"""Add audience targeting fields to Entity

Revision ID: 5600a3685d5e
Revises: d963c50bb263
Create Date: 2026-04-01 21:45:04.598005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5600a3685d5e'
down_revision = 'd963c50bb263'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign keys first
    op.drop_constraint('bands_role_id_fkey', 'bands', type_='foreignkey')
    
    # Drop tables (child then parent)
    op.drop_table('band_tone_keywords')
    op.drop_table('tone_keywords')
    op.drop_table('band_brand_values')
    op.drop_table('brand_values')
    op.drop_table('band_musical_genres')
    op.drop_table('musical_genres')
    op.drop_table('professional_roles')

    # Update columns
    op.add_column('band_contexts', sa.Column('key', sa.String(length=100), nullable=False))
    op.add_column('band_contexts', sa.Column('value', sa.Text(), nullable=True))
    op.drop_column('band_contexts', 'description')
    op.drop_column('band_contexts', 'start_date')
    op.drop_column('band_contexts', 'end_date')
    op.drop_column('band_contexts', 'event_type')
    op.drop_column('band_contexts', 'is_active')
    op.add_column('band_members', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('band_members', 'image_urls')
    op.drop_column('band_members', 'training_status')
    op.drop_column('band_members', 'metadata')
    op.drop_column('band_members', 'lora_trained')
    op.drop_column('band_members', 'lora_replicate_model_id')
    op.add_column('bands', sa.Column('audience_age_min', sa.Integer(), nullable=True))
    op.add_column('bands', sa.Column('audience_age_max', sa.Integer(), nullable=True))
    op.add_column('bands', sa.Column('audience_country', sa.String(length=100), nullable=True))
    op.add_column('bands', sa.Column('audience_province', sa.String(length=100), nullable=True))
    op.add_column('bands', sa.Column('use_regional_slang', sa.Boolean(), nullable=True))
    op.alter_column('bands', 'genre',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_column('bands', 'profession')
    op.drop_column('bands', 'learning_notes')
    op.drop_column('bands', 'upcoming_events')
    op.drop_column('bands', 'brand_colors')
    op.drop_column('bands', 'visual_identity_vector')
    op.drop_column('bands', 'role_id')
    op.drop_column('bands', 'visual_style')
    op.drop_column('bands', 'visual_lighting')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
