"""Add agentic models for curating and learning

Revision ID: d963c50bb263
Revises: 16ae00b756b1
Create Date: 2026-03-29 22:51:34.116259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'd963c50bb263'
down_revision: Union[str, None] = '16ae00b756b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bands', sa.Column('visual_identity_vector', Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bands', 'visual_identity_vector')
    # ### end Alembic commands ###
